version: 2
updates:
  # Aktualizacje zależności Pythonowych
  - package-ecosystem: "pip"
    directory: "/requirements" # Katalog z plikami requirements
    schedule:
      interval: "weekly" # Cotygodniowe sprawdzanie aktualizacji
    open-pull-requests-limit: 3 # Maksymalnie 3 otwarte PR-y
    labels:
      - dependencies
      - python
    commit-message:
      prefix: "deps(pip):"
    groups:
      all-dependencies:
        patterns:
          - ".*" # Grupowanie wszystkich zależności w jedno zgłoszenie

  # Aktualizacje GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Katalog z plikami GitHub Actions
    schedule:
      interval: "weekly" # Cotygodniowe sprawdzanie aktualizacji
    open-pull-requests-limit: 3 # Maksymalnie 3 otwarte PR-y
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "deps(actions):"
    groups:
      all-actions:
        patterns:
          - ".*" # Grupowanie wszystkich zależności w jedno zgłoszenie
