version: 2
updates:
  # Aktualizacje zależności Pythonowych
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    prune-stale-branches: true
    labels:
      - dependencies
      - python
    commit-message:
      prefix: "deps(pip):"
    groups:
      all-dependencies:
        patterns:
          - ".*"
    security-updates: true

  # Aktualizacje GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    prune-stale-branches: true
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "deps(actions):"
    groups:
      all-actions:
        patterns:
          - ".*"
    security-updates: true
