version: 2
updates:
  # Aktualizacje zależności Pythonowych
  - package-ecosystem: "pip"
    directory: "/requirements" # Katalog z plikami requirements
    schedule:
      interval: "weekly" # Cotygodniowe sprawdzanie aktualizacji
    open-pull-requests-limit: 1 # Ograniczenie do jednego PR
    groups:
      all-dependencies:
        patterns:
          - ".*" # Grupowanie wszystkich zależności w jeden PR

  # Aktualizacje GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Dla plików workflow w katalogu .github/workflows/
    schedule:
      interval: "weekly" # Cotygodniowe sprawdzanie aktualizacji
    open-pull-requests-limit: 1 # Ograniczenie do jednego PR
    groups:
      all-actions:
        patterns:
          - ".*" # Grupowanie wszystkich zależności GitHub Actions w jeden PR
