name: Static Code Analysis and Security Testing

on:
  push:
    branches:
      - main
      - stable
  pull_request:
    branches:
      - '*'

jobs:
  static-analysis:
    name: Static Code Analysis and Security Testing
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: requirements/*.txt

      # 3) Install dependencies
      - name: Install Dependencies
        run: |
          pip install -r requirements/dev.txt

      # 4) Start Flask Application
      - name: Start Flask App
        run: |
          nohup python app.py &
        working-directory: ./tests/test_apps/exampleflaskapp
        env:
          FLASK_APP: app.py
          FLASK_ENV: development

      # 5) Wait for Flask to Start
      - name: Wait for Flask to Start
        run: sleep 10

      # 6) Pull OWASP ZAP Docker Image
      - name: Pull OWASP ZAP Image
        run: |
          docker pull owasp/zap2docker

      # 7) Start OWASP ZAP in Docker
      - name: Start OWASP ZAP
        run: |
          docker run -d --name zap -u zap -p 8080:8080 -v $PWD/reports:/zap/reports owasp/zap2docker zap.sh -daemon -port 8080 -host 0.0.0.0

      # 8) Wait for OWASP ZAP to Start
      - name: Wait for OWASP ZAP to Start
        run: sleep 10

      # 9) Run OWASP ZAP Security Scan
      - name: Run OWASP ZAP Scan
        id: owasp-zap-scan
        run: |
          mkdir -p reports/zap
          docker exec zap zap-cli -p 8080 quick-scan --self-contained --spider -r http://localhost:5000
          docker exec zap zap-cli -p 8080 report -o /zap/reports/zap_report.html -f html

      # 10) Upload OWASP ZAP Report
      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: reports/zap/zap_report.html

      # 11) Run Flake8
      - name: Run Flake8
        id: flake8
        run: |
          mkdir -p reports/flake8
          flake8 src/ --format=html --htmldir=reports/flake8
        continue-on-error: true

      # 12) Run Bandit
      - name: Run Bandit
        id: bandit
        run: |
          mkdir -p reports/bandit
          bandit --exit-zero -r src/ -f html -o reports/bandit/bandit.html -ll
        continue-on-error: true

      # 13) Upload Flake8 Report
      - name: Upload Flake8 Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flake8-report
          path: reports/flake8

      # 14) Upload Bandit Report
      - name: Upload Bandit Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: reports/bandit/bandit.html

      # 15) Analysis Summary
      - name: Analysis Summary
        if: always()
        run: |
          if [ -d "reports/flake8" ]; then
            echo "Flake8 Analysis completed. Report uploaded."
          else
            echo "Flake8 Analysis failed or no report generated."
          fi
          if [ -f "reports/bandit/bandit.html" ]; then
            echo "Bandit Analysis completed. Report uploaded."
          else
            echo "Bandit Analysis failed or no report generated."
          fi
          if [ -f "reports/zap/zap_report.html" ]; then
            echo "OWASP ZAP Security Scan completed. Report uploaded."
          else
            echo "OWASP ZAP Security Scan failed or no report generated."
          fi

      # 16) Fail if analysis has errors
      - name: Fail if analysis has errors
        if: always()
        run: |
          if [ "${{ steps.flake8.outcome }}" == "failure" ]; then
            echo "Flake8 found issues. Marking job as failed."
            exit 1
          fi

          if [ "${{ steps.bandit.outcome }}" == "failure" ]; then
            echo "Bandit found issues. Marking job as failed."
            exit 1
          fi

          echo "Static analysis passed. Proceeding to OWASP ZAP results."

          if grep -q "FAIL-CRITICAL" reports/zap/zap_report.html; then
            echo "OWASP ZAP found critical vulnerabilities. Marking job as failed."
            exit 1
          fi

          echo "All analyses passed successfully."
