name: Static Code Analysis

on:
  push:
    branches:
      - main
      - stable
  pull_request:
    branches:
      - '*'

jobs:
  static-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: requirements/*.txt

      # 3) Install dependencies
      - name: Install Dependencies
        run: |
          pip install -r requirements/dev.txt

      # 4) Run Flake8 (continue-on-error, żeby nie przerwać joba przed uploadem)
      - name: Run Flake8
        id: flake8
        run: |
          mkdir -p reports/flake8
          flake8 src/ --format=html --htmldir=reports/flake8
        continue-on-error: true

      # 5) Run Bandit (continue-on-error, żeby nie przerwać joba przed uploadem)
      - name: Run Bandit
        id: bandit
        run: |
          mkdir -p reports/bandit
          # bandit -r src/ -f html -o reports/bandit/bandit.html -ll
          bandit --exit-zero -r src/ -f html -o reports/bandit/bandit.html -ll
        continue-on-error: true

      # 6) Zawsze uploaduj Flake8 Report
      - name: Upload Flake8 Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flake8-report
          path: reports/flake8

      # 7) Zawsze uploaduj Bandit Report
      - name: Upload Bandit Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: reports/bandit/bandit.html

      # 8) Podsumowanie w logu
      - name: Analysis Summary
        if: always()
        run: |
          if [ -d "reports/flake8" ]; then
            echo "Flake8 Analysis completed. Report uploaded."
          else
            echo "Flake8 Analysis failed or no report generated."
          fi
          if [ -f "reports/bandit/bandit.html" ]; then
            echo "Bandit Analysis completed. Report uploaded."
          else
            echo "Bandit Analysis failed or no report generated."
          fi

      # 9) Ostateczny krok decydujący o failu joba, jeśli Flake8/Bandit wykazały błędy
      - name: Fail if analysis has errors
        # "if: always()" – uruchomi się nawet, gdy poprzednie kroki są w statusie failure
        if: always()
        run: |
          if [ "${{ steps.flake8.outcome }}" == "failure" ]; then
            echo "Flake8 found issues. Marking job as failed."
            exit 1
          fi

          if [ "${{ steps.bandit.outcome }}" == "failure" ]; then
            echo "Bandit found issues. Marking job as failed."
            exit 1
          fi

          echo "Both Flake8 and Bandit passed without critical errors."
